# Generated by Django 5.1 on 2025-11-13 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_files", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                ("file_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="원본 파일명"),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="저장된 파일명")),
                ("file_size", models.BigIntegerField(verbose_name="파일 크기(bytes)")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "이미지"),
                            ("video", "영상"),
                            ("screenshot", "스크린샷"),
                            ("document", "문서"),
                        ],
                        max_length=20,
                        verbose_name="파일 유형",
                    ),
                ),
                ("file_format", models.CharField(max_length=10, verbose_name="파일 확장자")),
                ("mime_type", models.CharField(max_length=100, verbose_name="MIME 타입")),
                (
                    "storage_type",
                    models.CharField(
                        choices=[("local", "로컬"), ("s3", "S3")],
                        default="local",
                        max_length=10,
                        verbose_name="저장 위치",
                    ),
                ),
                ("file_path", models.TextField(verbose_name="파일 경로")),
                (
                    "s3_key",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="S3 키"
                    ),
                ),
                (
                    "s3_bucket",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="S3 버킷"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("detection", "딥페이크 분석"),
                            ("protection", "콘텐츠 보호"),
                            ("zoom", "Zoom 감시"),
                            ("report", "신고 증거"),
                        ],
                        max_length=20,
                        verbose_name="사용 목적",
                    ),
                ),
                (
                    "is_temporary",
                    models.BooleanField(default=False, verbose_name="임시 파일 여부"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "related_model",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="연결된 모델"
                    ),
                ),
                (
                    "related_record_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="연결된 레코드 ID"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, null=True, verbose_name="추가 메타데이터"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="삭제일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "미디어 파일",
                "verbose_name_plural": "미디어 파일 목록",
                "db_table": "media_files",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="media_files_created_72bc9d_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="media_files_user_id_0814ea_idx",
                    ),
                    models.Index(
                        fields=["purpose"], name="media_files_purpose_7d264f_idx"
                    ),
                    models.Index(
                        fields=["is_temporary"], name="media_files_is_temp_cd5b17_idx"
                    ),
                    models.Index(
                        fields=["is_deleted"], name="media_files_is_dele_037c65_idx"
                    ),
                ],
            },
        ),
    ]
