# Generated by Django 5.1 on 2025-11-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsetting",
            name="zoom_capture_interval",
            field=models.IntegerField(default=3, verbose_name="Zoom 캡처 간격(초)"),
        ),
    ]
