# Generated by Django 5.1 on 2025-11-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_appsetting_zoom_capture_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="프로필 이미지 경로"
            ),
        ),
    ]
