# Generated by Django 5.1 on 2025-11-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrecord",
            name="detection_details",
            field=models.JSONField(
                blank=True,
                help_text='[{"person_id": 1, "is_deepfake": true, "confidence": 95.5, "detection_image_url": "https://..."}]',
                null=True,
                verbose_name="상세 탐지 결과",
            ),
        ),
        migrations.AddField(
            model_name="analysisrecord",
            name="heatmap_path",
            field=models.TextField(blank=True, null=True, verbose_name="히트맵 이미지 경로"),
        ),
        migrations.AlterField(
            model_name="analysisrecord",
            name="confidence_score",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="신뢰도 점수 (%)"
            ),
        ),
        migrations.DeleteModel(name="FaceDetectionResult",),
    ]
